name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: self-hosted
    environment: MONGO_URI
    strategy:
      matrix:
        node-version: [20]   # use 22 if you installed Node 22 on EC2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # (Tutorial demo) print env secrets — OK for class, not for real prod
      - name: Print Env Secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "Secret 1 is: $MONGO_URI"
          echo "Secret 2 is: $JWT_SECRET"
          echo "Secret 3 is: $PORT"

      - name: Stop PM2 if running
        run: pm2 stop all || true

      # ----- BACKEND -----
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      # ----- FRONTEND -----
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          df -h
          rm -rf build || true
          npm run build

      # ----- Write .env for production (CD) -----
      - name: Create .env from PROD secret
        working-directory: backend
        run: |
          rm -f .env
          printf "%s" "${{ secrets.PROD }}" > .env

      # ----- PM2 start/restart (CD) -----
      - name: Start/Restart Backend with PM2
        working-directory: backend
        run: |
          pm2 describe backend >/dev/null 2>&1 && pm2 restart backend || pm2 start "npm run start" --name backend

      - name: Serve Frontend with PM2
        working-directory: frontend
        run: |
          pm2 describe Frontend >/dev/null 2>&1 && pm2 restart Frontend || pm2 serve build 3000 --name Frontend --spa

      - name: Save PM2 process list
        run: pm2 save


